  ak:
    outputs:
        dev:
            dbname: "{{ env_var('POSTGRES_DBNAME') }}"
            host: "{{ env_var('POSTGRES_HOST') }}"
            pass: "{{ env_var('POSTGRES_PASSWORD') }}"
            port: {{ env_var('POSTGRES_PORT') }}
            schema: space
            threads: {{ env_var('DBT_THREADS', 4) }}
            type: postgres
            user: "{{ env_var('POSTGRES_USER') }}"
