version: '3'
services:
  magic:
    image: mageai/mageai:latest
    container_name: ak-local
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/${PROJECT_NAME}
    restart: on-failure:5
    networks:
      - mage
  postgres:
    image: postgres:latest
    container_name: db_mage
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mage

networks:
  mage:
    driver: bridge

volumes:
  postgres_data:

