version: '3'
services:
  magic:
    image: mageai/mageai:latest
    container_name: ak-local
    command: mage start ak-local
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /Users/alok/Documents/project_code/codvo_projects/mage-ai
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - .:/Users/alok/Documents/project_code/codvo_projects/mage-ai
    restart: on-failure:5

