sync_config:
  auth_type: null
  branch: master
  email: alok.kashimath@codvo.ai
  remote_repo_link: https://github.com/tesalok/ak-mage-ai.git
  repo_path: /home/src
  ssh_private_key_secret_name: mage_git_ssh_private_key_b64
  ssh_public_key_secret_name: mage_git_ssh_public_key_b64
  sync_on_pipeline_run: null
  sync_on_start: true
  sync_submodules: null
  type: null
  username: tesalok
